taxonomy = {
    cookingMethods: [
        'Bakken',
        'Frituren',
        'Grillen',
        'Koken',
        'Oven',
        'Pureren',
        'Roken',
        'Stomen',
        'Stoven',
        'Sudderen',
        'Wokken'
    ],

    cookingTime: [
        '1 Hour',
        '10 minutes',
        '15 minutes',
        '2 Hour',
        '20 minutes',
        '3 Hour',
        '30 minutes',
        '45 minutes',
        '5 minutes',
        'More than 3 hours'
    ],

    courses: [
        'Bijgerecht',
        'Hoofdgerecht',
        'Lunch',
        'Nagerecht',
        'Ontbijt',
        'Tussendoortje',
        'Tussengerecht',
        'Voorgerecht'
    ],

    ingredients: [
        'Benodigdheden/Aluminiumfolie',
        'Benodigdheden/Bakpapier',
        'Benodigdheden/Huishoudfolie',
        'Benodigdheden',
        'Fruit/Aardbei',
        'Fruit/Appel',
        'Fruit/Avocado',
        'Fruit/Banaan',
        'Fruit/Citroen',
        'Fruit/Framboos',
        'Fruit/Kersen',
        'Fruit/Kiwi',
        'Fruit/Limoen',
        'Fruit/Mandarijn',
        'Fruit/Mango',
        'Fruit/Meloen',
        'Fruit/Perzik',
        'Fruit/Sinaasappel',
        'Fruit/Tutti-frutti',
        'Fruit/Watermeloen',
        'Fruit',
        'Groenten/Amsoi',
        'Groenten/Andijvie',
        'Groenten/Aubergine',
        'Groenten/Augurk',
        'Groenten/Asperge',
        'Groenten/Bleekselderij',
        'Groenten/Bloemkool',
        'Groenten/Boerenkool',
        'Groenten/Broccoli',
        'Groenten/Champignons en paddestoelen/Bospaddestoelen',
        'Groenten/Champignons en paddestoelen/Canterellen',
        'Groenten/Champignons en paddestoelen/Champignons',
        'Groenten/Champignons en paddestoelen/Eekhoorntjesbrood',
        'Groenten/Champignons en paddestoelen/Oesterzwam',
        'Groenten/Champignons en paddestoelen',
        'Groenten/Chinese kool',
        'Groenten/Courgette',
        'Groenten/Doperwten',
        'Groenten/Gedroogde gebakken uitjes',
        'Groenten/Kappertjes',
        'Groenten/Komkommer',
        'Groenten/Mais',
        'Groenten/Paksoi',
        'Groenten/Paprika/Rode paprika',
        'Groenten/Paprika',
        'Groenten/Pot gegrilde rode paprika',
        'Groenten/Prei',
        'Groenten/Radijs',
        'Groenten/Rettich',
        'Groenten/Sla/Ijsbergsla',
        'Groenten/Sla/Kropsla',
        'Groenten/Sla/Rucola',
        'Groenten/Sla/Veldsla',
        'Groenten/Sla/Waterkers',
        'Groenten/Sla',
        'Groenten/Snijbonen',
        'Groenten/Sperziebonen',
        'Groenten/Spinazie',
        'Groenten/Sugarsnaps',
        'Groenten/Tomaat/Cherrytomaat',
        'Groenten/Tomaat/Tomatenblokjes uit blik',
        'Groenten/Tomaat/Tomatenpuree',
        'Groenten/Tomaat/Vleestomaat',
        'Groenten/Tomaat/Vleestomaten',
        'Groenten/Tomaat/Zongedroogde tomaat',
        'Groenten/Tomaat',
        'Groenten/Uien/Bosui',
        'Groenten/Uien/Rode ui',
        'Groenten/Uien/Sjalot',
        'Groenten/Uien/Ui',
        'Groenten/Uien',
        'Groenten/Venkel',
        'Groenten/Wortel',
        'Groenten/Zuurkool',
        'Groenten',
        'Kaas/Feta',
        'Kaas/Grana',
        'Kaas/Mozzarella',
        'Kaas/Oude kaas',
        'Kaas/Parmezaan',
        'Kaas/Pecorino',
        'Kaas/Schapenkaas',
        'Kaas',
        'Koolhydraten/Aardappelen/Krieltjes',
        'Koolhydraten/Aardappelen',
        'Koolhydraten/Zoete aardappelen',
        'Koolhydraten/Beschuit',
        'Koolhydraten/Bladerdeeg',
        'Koolhydraten/Brood',
        'Koolhydraten/Couscous',
        'Koolhydraten/Deeg',
        'Koolhydraten/Noodles/Bami',
        'Koolhydraten/Noodles',
        'Koolhydraten/Wrap',
        'Koolhydraten',
        'Kruiden/Ajwain',
        'Kruiden/Asafoetida',
        'Kruiden/Basilicum',
        'Kruiden/Bieslook',
        'Kruiden/Cajunkruiden',
        'Kruiden/Cassave',
        'Kruiden/Cayennepeper',
        'Kruiden/Chilipeper',
        'Kruiden/Chilipoeder',
        'Kruiden/Citroengras',
        'Kruiden/Colorozozout',
        'Kruiden/Curry bladeren',
        'Kruiden/Dille',
        'Kruiden/Fenegriek',
        'Kruiden/Gember',
        'Kruiden/Kamiri Noten',
        'Kruiden/Kaneel',
        'Kruiden/Kardemom',
        'Kruiden/Karwijzaad',
        'Kruiden/Kerrie',
        'Kruiden/Knoflook',
        'Kruiden/Komijn',
        'Kruiden/Koriander',
        'Kruiden/Kruidenmix kip zonder zout',
        'Kruiden/Kruidnagel',
        'Kruiden/Laurier',
        'Kruiden/Masala/Garam Masala',
        'Kruiden/Masala/Tandoori Masala',
        'Kruiden/Masala',
        'Kruiden/Mosterd',
        'Kruiden/Mosterdpoeder',
        'Kruiden/Nootmuskaat',
        'Kruiden/Oregano',
        'Kruiden/Paprikapoeder',
        'Kruiden/Peper',
        'Kruiden/Peterselie',
        'Kruiden/Rozemarijn',
        'Kruiden/Sesamzaad',
        'Kruiden/Spaanse peper',
        'Kruiden/Suiker',
        'Kruiden/Tijm',
        'Kruiden/Turmeric',
        'Kruiden/Venkelzaad',
        'Kruiden/Witte peper',
        'Kruiden/Zout',
        'Kruiden',
        'Noten en peulvruchten/Amandelen',
        'Noten en peulvruchten/Olijven/Groene olijven',
        'Noten en peulvruchten/Olijven/Mediteraanse olijven',
        'Noten en peulvruchten/Olijven/Zwarte olijven',
        'Noten en peulvruchten/Olijven',
        'Noten en peulvruchten/Pijnboompitten',
        'Noten en peulvruchten/Rozijnen',
        'Noten en peulvruchten',
        'Overig/Bloem',
        'Overig/Ei',
        'Overig/Gist',
        'Overig/Maizena',
        'Overig/Meel',
        'Overig/Paneermeel',
        'Overig/Suiker/Basterdsuiker',
        'Overig/Suiker',
        'Overig',
        'Sauzen/Barbequesaus',
        'Sauzen/Honing mosterd',
        'Sauzen/Honing',
        'Sauzen/Ketjap',
        'Sauzen/Mayonaise',
        'Sauzen/Mosterd',
        'Sauzen/Pesto',
        'Sauzen/Tabasco',
        'Sauzen/Vissaus',
        'Sauzen/Worcestersaus',
        'Sauzen',
        'Vis/Forel',
        'Vis/Gamba\'s',
        'Vis/Garnalen',
        'Vis/Kabeljauw',
        'Vis/Paling',
        'Vis/Slibtong',
        'Vis/Zalm',
        'Vis',
        'Vlees en gevogelte/Eend',
        'Vlees en gevogelte/Hert/Hertenbiefstuk',
        'Vlees en gevogelte/Hert',
        'Vlees en gevogelte/Kalkoen',
        'Vlees en gevogelte/Kip/Drumsticks',
        'Vlees en gevogelte/Kip/Hele Kip',
        'Vlees en gevogelte/Kip/Kipfilet',
        'Vlees en gevogelte/Kip/Kippenborst',
        'Vlees en gevogelte/Kip/Kippengehakt',
        'Vlees en gevogelte/Kip',
        'Vlees en gevogelte/Lam/Lamsbout',
        'Vlees en gevogelte/Lam/Lamskoteletjes',
        'Vlees en gevogelte/Lam/Lamsschouder',
        'Vlees en gevogelte/Lam',
        'Vlees en gevogelte/Rund/Biefstuk',
        'Vlees en gevogelte/Rund/EntrecÃ´te',
        'Vlees en gevogelte/Rund/Gehakt',
        'Vlees en gevogelte/Rund/Rundergehakt',
        'Vlees en gevogelte/Rund',
        'Vlees en gevogelte/Rundvlees/Filet americain',
        'Vlees en gevogelte/Rundvlees/Runderlappen',
        'Vlees en gevogelte/Rundvlees',
        'Vlees en gevogelte/Varken/Ham',
        'Vlees en gevogelte/Varken/Hamlappen',
        'Vlees en gevogelte/Varken/Karbonade',
        'Vlees en gevogelte/Varken/Rookworst',
        'Vlees en gevogelte/Varken/Salami',
        'Vlees en gevogelte/Varken/Spek/Pancetta',
        'Vlees en gevogelte/Varken/Spek',
        'Vlees en gevogelte/Varken/Speklappen',
        'Vlees en gevogelte/Varken/Varkensdarm',
        'Vlees en gevogelte/Varken/Varkensfilet',
        'Vlees en gevogelte/Varken/Varkensschouder',
        'Vlees en gevogelte/Varken/Varkensworst',
        'Vlees en gevogelte/Varken',
        'Vlees en gevogelte/Wild',
        'Vlees en gevogelte',
        'Vloeistof/Azijn en zuren/Appel azijn',
        'Vloeistof/Azijn en zuren/Balsamico',
        'Vloeistof/Azijn en zuren/Citroensap',
        'Vloeistof/Azijn en zuren/Rijst azijn',
        'Vloeistof/Azijn en zuren/Rode wijnazijn',
        'Vloeistof/Azijn en zuren/Vijgen- pruimen azijn',
        'Vloeistof/Azijn en zuren/Witte wijnazijn',
        'Vloeistof/Azijn en zuren',
        'Vloeistof/Bouillon/Groentebouillon',
        'Vloeistof/Bouillon/Kippenbouillon',
        'Vloeistof/Bouillon/Paddestoelenbouillon',
        'Vloeistof/Bouillon/Runderbouillon',
        'Vloeistof/Bouillon/Visbouillon',
        'Vloeistof/Bouillon/Vleesbouillon',
        'Vloeistof/Bouillon',
        'Vloeistof/Drank/Cognac',
        'Vloeistof/Drank/Sherry',
        'Vloeistof/Drank/Whiskey',
        'Vloeistof/Drank/Wodka',
        'Vloeistof/Drank',
        'Vloeistof/Fond/Gevogeltefond',
        'Vloeistof/Fond/Wildfond',
        'Vloeistof/Fond',
        'Vloeistof/Olijfolie/Truffelolie',
        'Vloeistof/Olijfolie',
        'Vloeistof/Wijn/Riesling',
        'Vloeistof/Wijn/Rode wijn',
        'Vloeistof/Wijn/Witte wijn',
        'Vloeistof/Wijn',
        'Vloeistof/Zonnebloemolie',
        'Vloeistof',
        'Zuivel/Boter',
        'Zuivel/Creme fraiche',
        'Zuivel/Koffieroom',
        'Zuivel/Kokosmelk',
        'Zuivel/Kookroom',
        'Zuivel/Melk',
        'Zuivel/Slagroom',
        'Zuivel/Yoghurt',
        'Zuivel'
    ],

    kitchen: [
        'Aziatisch',
        'Frans',
        'Indiaas',
        'Italiaans',
        'Mediterraans',
        'Nederlands',
        'Oost-Europees',
        'Zuid-Amerikaans'
    ],

    mealTypes: [
        'Aardappels Groente Vlees',
        'Broodje',
        'Curry',
        'Ovenschotel',
        'Pasta',
        'Pizza',
        'Rijst',
        'Risotto',
        'Salade',
        'Sap, smoothies, milkshakes etc.',
        'Soep',
        'Stoofpot',
        'Taart',
        'Worst',
        'Wraps'
    ],

    prepTime: [
        '0 - 5 minutes',
        '5 - 15 minutes',
        '15 - 30 minutes',
        '30 - 60 minutes',
        '60+ minutes'
    ]
}
